def action
def runner = "ENOCH"
def claudePrompt = ""

pipeline {
    agent any
//  parameters {
//   credentials credentialType: 'com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl', defaultValue: 'AWS_CREDS_AUTOMATION_ACCT', name: 'AWS_AUTOMATION_ACCOUNT_CRED', required: false
// }

    parameters {
        choice(
            name: 'ACTION', 
            choices: ['full', 'image_build', 'tf_apply_scan', 'tf_destroy'], 
            description: """
            'full': Build AMI, Deploy Infrastructure, and Run Vulnerability Scan
            'image_build': Build AMI only
            'tf_apply_scan': Deploy terraform infrastructure and run vulnerability scan
            'tf_destroy': Destroy terraform infrastructure
            """
        )
    }

    environment {
        PATH = "${PATH}:${getTerraformPath()}"
        AMI_ID="ami-stack-${BUILD_NUMBER}"
        VERSION = "1.0.${BUILD_NUMBER}"
        // LLM_API_KEY = credentials('Claude_API')
    }

    stages{

         stage('Initial Stage') {
              steps {
                script {
                // def userInput = input(id: 'confirm', message: 'Start Pipeline?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Start Pipeline', name: 'confirm'] ])
                if (params.ACTION == 'full') {
                    action = "FULL PIPELINE BUILD"
                } else if (params.ACTION == 'image_build') {
                    action = "PACKER IMAGE BUILD"
                } else if (params.ACTION == 'tf_apply_scan') {
                    action = "TERRAFORM APPLY AND VULNERABILITY SCAN"
                } else if (params.ACTION == 'tf_destroy') {
                    action = "TERRAFORM DESTROY"
                } else {
                    action = "TINKERING..."
                }
            }
           }
        }

        stage('Checkout and load prompt') {
            steps {
                script {
                    def promptFile = 'CLIXX-AMI-BUILD/stackterraform/images/ai-source-audit-prompt.txt'

                    if (fileExists(promptFile)) {
                        claudePrompt = readFile(file: promptFile, encoding: 'UTF-8').trim()
                        echo "Successfully loaded AI prompt file as string"
                    } else {
                        error "Required prompt file: '${promptFile}' was not found in the workspace"
                    }

                }
            }
        }

        stage('AI Source Code Audit') {
            steps {
                slackSend (color: '#FFFF00', message: "runner: ${runner}, STARTING AI Code Audit ${action}: Job '${env.JOB_BASE_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                withCredentials([
                    string(credentialsId: 'Claude_API', variable: 'ANTHROPIC_API_KEY'),
                    string(credentialsId: 'GITHUB_TOKEN', variable: 'GH_TOKEN')
                ]) {
                    aiAgent(
                        agent: claudeCode(),
                        model: 'claude-sonnet-5', 
                        // prompt: 'Scan the project files in the workspace, check for hardcoded secrets, and fix any minor syntax errors in main.tf',
                        prompt: claudePrompt,               
                        yoloMode: true,
                        requireApprovals: false,
                        // apiCredentialsId: '${}'
                    )
                }
            }
        }

        stage('Packer AMI Build') {
            when { expression { params.ACTION == 'full' || params.ACTION == 'image_build' } }
             steps {
                 slackSend (color: '#FFFF00', message: "runner: ${runner}, STARTING PACKER ${action}: Job '${env.JOB_BASE_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                 sh '''
                 cd CLIXX-AMI-BUILD/stackterraform/images
                 sed -i "s/ami-stack-[0-9]*/${AMI_ID}/" ./image.pkr.hcl
                 export PACKER_LOG=1
                 export PACKER_LOG_PATH=$WORKSPACE/packer.log
                 /usr/bin/packer build -force image.pkr.hcl 
                 '''
            }
         }

        stage('Terraform init') {
            when { expression { params.ACTION == 'full' || params.ACTION == 'tf_apply_scan' || params.ACTION == 'tf_destroy' } }
             steps {
                 sh """
                 cd CLIXX-AMI-BUILD/stackterraform/instances
                 terraform init -upgrade 
                 """                  
            }
         }

        stage('Terraform Plan') {
            when { expression { params.ACTION == 'full' || params.ACTION == 'tf_apply_scan' || params.ACTION == 'tf_destroy' } }
             steps {
                 sh """
                 cd CLIXX-AMI-BUILD/stackterraform/instances
                 terraform plan -out=tfplan -input=false ${params.ACTION == 'tf_destroy' ? '-destroy' : ''}
                 """                          
            }
        }

        stage('Build Instance') {
            when { expression { params.ACTION == 'full' || params.ACTION == 'tf_apply_scan' } }
             steps {
                 sh """
                 cd CLIXX-AMI-BUILD/stackterraform/instances
                 terraform apply -auto-approve
                 """                          
            }
        }

        //   stage('Run Ansible Playbook'){
        //      steps {
        //          sh """
        //          cd Packer/CLIXX-AMI-BUILD/stackterraform/instances
        //          ansible -v
        //          """  
        //          slackSend (color: '#FFFF00', message: "ENDING DEPLOYMENT: Job '${env.JOB_BASE_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")                        
        //  }
        //  }

        stage('Build Vulnerability Report') {
            when { expression { params.ACTION == 'full' || params.ACTION == 'tf_apply_scan' } }
            steps {
                sh """
                cd CLIXX-AMI-BUILD/stackterraform/instances
                aws inspector2 list-findings --region us-east-1 \
                --query 'findings[].{Title:title,Severity:severity,Resource:resources[0].id}' \
                --output table
                aws inspector2 list-findings --region us-east-1 --output json > inspector-findings.json
                """
                archiveArtifacts artifacts: 'CLIXX-AMI-BUILD/stackterraform/instances/inspector-findings.json', allowEmptyArchive: true
                slackSend (color: '#1fe139', message: "runner: ${runner}, ENDING ${action}: Job '${env.JOB_BASE_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            }
        }

        stage('Destroy Instance') {
            when { expression { params.ACTION == 'tf_destroy' } }
             steps {
                 slackSend (color: '#FFFF00', message: "runner: ${runner}, STARTING ${action}: Job '${env.JOB_BASE_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                 sh """
                 cd CLIXX-AMI-BUILD/stackterraform/instances
                 terraform destroy -auto-approve
                 """                          
            }
        }
    }

    post {
        failure {
            slackSend(
                channel: '#stackjenkins',
                color: 'danger',
                message: "FAILED: ${env.JOB_BASE_NAME} #${env.BUILD_NUMBER} (${env.BUILD_URL})"
            )
        }
        success {
            slackSend(
                channel: '#stackjenkins',
                color: 'good',
                message: "SUCCESS: ${env.JOB_BASE_NAME} #${env.BUILD_NUMBER}"
            )
        }
    }
}

def getTerraformPath(){
    def tfHome= tool name: 'terraform-1.10', type: 'terraform'
    return tfHome
}

def getNodeJsPath(){
    def njshome= tool name: 'nodejs26', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
    return njshome
}

//  def getAnsiblePath(){
//         def AnsibleHome= tool name: 'Ansible', type: 'org.jenkinsci.plugins.ansible.AnsibleInstallation'
//         return AnsibleHome
//     }

// def getPackerPath(){
//        def PackerHome= tool name: 'Packer', type: 'biz.neustar.jenkins.plugins.packer.PackerInstallation'
//     }